---
  - name: "create web directory"
    file:
      path: ~/web
      state: directory
  - name: "Copy web artifact"
    template:
      src: "../../../../../artifact.tar.gz"
      dest: "~/web/artifact.tar.gz"
  - name: "unzip artifact"
    unarchive:
      src: ~/web/artifact.tar.gz
      dest: ~/web/      
  - name: Excuting node
    shell: |
      cd ~/web
      pm2 stop default
      pm2 start npm -- start